### ISSUE TITLE
code behavior block?

### ISSUE THREAD

**Issue by jossse69** [KutayGuler/emojistan#16]
this is a cool idea i had in my mind... coding is fun for me idk

**Comment by KutayGuler** [comment]
That would require a language server to check the correctness of the syntax and making sure the user doesn't break the app. Which are all too high effort things for a game with zero users xD

The closest rulebox is the Sequencer. It lets the user execute some functions like `spawn`, `destroy`, `paint` etc.

**Comment by jossse69** [comment]
yea, sorry idk
